# Generated by Django 3.2 on 2021-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_data_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/pdfs'),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(upload_to='static/uploads/images'),
        ),
    ]
